/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.tags.service.base;

import com.liferay.asset.tags.model.AssetTagDepotEntryRel;
import com.liferay.asset.tags.service.AssetTagDepotEntryRelLocalService;
import com.liferay.asset.tags.service.persistence.AssetTagDepotEntryRelPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the asset tag depot entry rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.tags.service.impl.AssetTagDepotEntryRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.tags.service.impl.AssetTagDepotEntryRelLocalServiceImpl
 * @generated
 */
public abstract class AssetTagDepotEntryRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AssetTagDepotEntryRelLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetTagDepotEntryRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.asset.tags.service.AssetTagDepotEntryRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asset tag depot entry rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetTagDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetTagDepotEntryRel the asset tag depot entry rel
	 * @return the asset tag depot entry rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetTagDepotEntryRel addAssetTagDepotEntryRel(
		AssetTagDepotEntryRel assetTagDepotEntryRel) {

		assetTagDepotEntryRel.setNew(true);

		return assetTagDepotEntryRelPersistence.update(assetTagDepotEntryRel);
	}

	/**
	 * Creates a new asset tag depot entry rel with the primary key. Does not add the asset tag depot entry rel to the database.
	 *
	 * @param assetTagDepotEntryRelId the primary key for the new asset tag depot entry rel
	 * @return the new asset tag depot entry rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetTagDepotEntryRel createAssetTagDepotEntryRel(
		long assetTagDepotEntryRelId) {

		return assetTagDepotEntryRelPersistence.create(assetTagDepotEntryRelId);
	}

	/**
	 * Deletes the asset tag depot entry rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetTagDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetTagDepotEntryRelId the primary key of the asset tag depot entry rel
	 * @return the asset tag depot entry rel that was removed
	 * @throws PortalException if a asset tag depot entry rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetTagDepotEntryRel deleteAssetTagDepotEntryRel(
			long assetTagDepotEntryRelId)
		throws PortalException {

		return assetTagDepotEntryRelPersistence.remove(assetTagDepotEntryRelId);
	}

	/**
	 * Deletes the asset tag depot entry rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetTagDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetTagDepotEntryRel the asset tag depot entry rel
	 * @return the asset tag depot entry rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetTagDepotEntryRel deleteAssetTagDepotEntryRel(
		AssetTagDepotEntryRel assetTagDepotEntryRel) {

		return assetTagDepotEntryRelPersistence.remove(assetTagDepotEntryRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return assetTagDepotEntryRelPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssetTagDepotEntryRel.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetTagDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.tags.model.impl.AssetTagDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assetTagDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.tags.model.impl.AssetTagDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assetTagDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetTagDepotEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assetTagDepotEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssetTagDepotEntryRel fetchAssetTagDepotEntryRel(
		long assetTagDepotEntryRelId) {

		return assetTagDepotEntryRelPersistence.fetchByPrimaryKey(
			assetTagDepotEntryRelId);
	}

	/**
	 * Returns the asset tag depot entry rel with the matching UUID and company.
	 *
	 * @param uuid the asset tag depot entry rel's UUID
	 * @param companyId the primary key of the company
	 * @return the matching asset tag depot entry rel, or <code>null</code> if a matching asset tag depot entry rel could not be found
	 */
	@Override
	public AssetTagDepotEntryRel fetchAssetTagDepotEntryRelByUuidAndCompanyId(
		String uuid, long companyId) {

		return assetTagDepotEntryRelPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the asset tag depot entry rel with the primary key.
	 *
	 * @param assetTagDepotEntryRelId the primary key of the asset tag depot entry rel
	 * @return the asset tag depot entry rel
	 * @throws PortalException if a asset tag depot entry rel with the primary key could not be found
	 */
	@Override
	public AssetTagDepotEntryRel getAssetTagDepotEntryRel(
			long assetTagDepotEntryRelId)
		throws PortalException {

		return assetTagDepotEntryRelPersistence.findByPrimaryKey(
			assetTagDepotEntryRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assetTagDepotEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetTagDepotEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetTagDepotEntryRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assetTagDepotEntryRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AssetTagDepotEntryRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetTagDepotEntryRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assetTagDepotEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetTagDepotEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetTagDepotEntryRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetTagDepotEntryRelPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AssetTagDepotEntryRelLocalServiceImpl#deleteAssetTagDepotEntryRel(AssetTagDepotEntryRel) to avoid orphaned data");
		}

		return assetTagDepotEntryRelLocalService.deleteAssetTagDepotEntryRel(
			(AssetTagDepotEntryRel)persistedModel);
	}

	@Override
	public BasePersistence<AssetTagDepotEntryRel> getBasePersistence() {
		return assetTagDepotEntryRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetTagDepotEntryRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the asset tag depot entry rel with the matching UUID and company.
	 *
	 * @param uuid the asset tag depot entry rel's UUID
	 * @param companyId the primary key of the company
	 * @return the matching asset tag depot entry rel
	 * @throws PortalException if a matching asset tag depot entry rel could not be found
	 */
	@Override
	public AssetTagDepotEntryRel getAssetTagDepotEntryRelByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return assetTagDepotEntryRelPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the asset tag depot entry rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.tags.model.impl.AssetTagDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset tag depot entry rels
	 * @param end the upper bound of the range of asset tag depot entry rels (not inclusive)
	 * @return the range of asset tag depot entry rels
	 */
	@Override
	public List<AssetTagDepotEntryRel> getAssetTagDepotEntryRels(
		int start, int end) {

		return assetTagDepotEntryRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset tag depot entry rels.
	 *
	 * @return the number of asset tag depot entry rels
	 */
	@Override
	public int getAssetTagDepotEntryRelsCount() {
		return assetTagDepotEntryRelPersistence.countAll();
	}

	/**
	 * Updates the asset tag depot entry rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetTagDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetTagDepotEntryRel the asset tag depot entry rel
	 * @return the asset tag depot entry rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetTagDepotEntryRel updateAssetTagDepotEntryRel(
		AssetTagDepotEntryRel assetTagDepotEntryRel) {

		return assetTagDepotEntryRelPersistence.update(assetTagDepotEntryRel);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AssetTagDepotEntryRelLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		assetTagDepotEntryRelLocalService =
			(AssetTagDepotEntryRelLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetTagDepotEntryRelLocalService.class.getName();
	}

	@Override
	public CTPersistence<AssetTagDepotEntryRel> getCTPersistence() {
		return assetTagDepotEntryRelPersistence;
	}

	@Override
	public Class<AssetTagDepotEntryRel> getModelClass() {
		return AssetTagDepotEntryRel.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<AssetTagDepotEntryRel>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(assetTagDepotEntryRelPersistence);
	}

	protected String getModelClassName() {
		return AssetTagDepotEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			assetTagDepotEntryRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected AssetTagDepotEntryRelLocalService
		assetTagDepotEntryRelLocalService;

	@Reference
	protected AssetTagDepotEntryRelPersistence assetTagDepotEntryRelPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetTagDepotEntryRelLocalServiceBaseImpl.class);

}