/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.web.internal.util;

import com.liferay.change.tracking.model.CTCollection;
import com.liferay.change.tracking.service.CTCollectionLocalServiceUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.FastDateFormatFactoryUtil;

import java.text.Format;

/**
 * @author David Truong
 */
public class SandboxUtil {

	public static CTCollection addSandboxCTCollection(long userId)
		throws PortalException {

		User user = UserLocalServiceUtil.getUser(userId);

		Format format = FastDateFormatFactoryUtil.getDateTime(
			user.getLocale(), user.getTimeZone());

		return CTCollectionLocalServiceUtil.addCTCollection(
			user.getCompanyId(), user.getUserId(),
			user.getScreenName() + " - " +
				format.format(System.currentTimeMillis()),
			LanguageUtil.get(
				user.getLocale(), "autogenerated-by-sandbox-only-mode"));
	}

}