/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Child service. Represents a row in the &quot;Child&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.change.tracking.sample.model.impl.ChildModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.change.tracking.sample.model.impl.ChildImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Child
 * @generated
 */
@ProviderType
public interface ChildModel
	extends BaseModel<Child>, CTModel<Child>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a child model instance should use the {@link Child} interface instead.
	 */

	/**
	 * Returns the primary key of this child.
	 *
	 * @return the primary key of this child
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this child.
	 *
	 * @param primaryKey the primary key of this child
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this child.
	 *
	 * @return the mvcc version of this child
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this child.
	 *
	 * @param mvccVersion the mvcc version of this child
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this child.
	 *
	 * @return the ct collection ID of this child
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this child.
	 *
	 * @param ctCollectionId the ct collection ID of this child
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the child ID of this child.
	 *
	 * @return the child ID of this child
	 */
	public long getChildId();

	/**
	 * Sets the child ID of this child.
	 *
	 * @param childId the child ID of this child
	 */
	public void setChildId(long childId);

	/**
	 * Returns the company ID of this child.
	 *
	 * @return the company ID of this child
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this child.
	 *
	 * @param companyId the company ID of this child
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this child.
	 *
	 * @return the name of this child
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this child.
	 *
	 * @param name the name of this child
	 */
	public void setName(String name);

	/**
	 * Returns the grand parent ID of this child.
	 *
	 * @return the grand parent ID of this child
	 */
	public long getGrandParentId();

	/**
	 * Sets the grand parent ID of this child.
	 *
	 * @param grandParentId the grand parent ID of this child
	 */
	public void setGrandParentId(long grandParentId);

	/**
	 * Returns the parent child ID of this child.
	 *
	 * @return the parent child ID of this child
	 */
	public long getParentChildId();

	/**
	 * Sets the parent child ID of this child.
	 *
	 * @param parentChildId the parent child ID of this child
	 */
	public void setParentChildId(long parentChildId);

	/**
	 * Returns the parent name of this child.
	 *
	 * @return the parent name of this child
	 */
	@AutoEscape
	public String getParentName();

	/**
	 * Sets the parent name of this child.
	 *
	 * @param parentName the parent name of this child
	 */
	public void setParentName(String parentName);

	@Override
	public Child cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}