/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GrandParent service. Represents a row in the &quot;GrandParent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.change.tracking.sample.model.impl.GrandParentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.change.tracking.sample.model.impl.GrandParentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GrandParent
 * @generated
 */
@ProviderType
public interface GrandParentModel
	extends BaseModel<GrandParent>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a grand parent model instance should use the {@link GrandParent} interface instead.
	 */

	/**
	 * Returns the primary key of this grand parent.
	 *
	 * @return the primary key of this grand parent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this grand parent.
	 *
	 * @param primaryKey the primary key of this grand parent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this grand parent.
	 *
	 * @return the mvcc version of this grand parent
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this grand parent.
	 *
	 * @param mvccVersion the mvcc version of this grand parent
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the grand parent ID of this grand parent.
	 *
	 * @return the grand parent ID of this grand parent
	 */
	public long getGrandParentId();

	/**
	 * Sets the grand parent ID of this grand parent.
	 *
	 * @param grandParentId the grand parent ID of this grand parent
	 */
	public void setGrandParentId(long grandParentId);

	/**
	 * Returns the company ID of this grand parent.
	 *
	 * @return the company ID of this grand parent
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this grand parent.
	 *
	 * @param companyId the company ID of this grand parent
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this grand parent.
	 *
	 * @return the name of this grand parent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this grand parent.
	 *
	 * @param name the name of this grand parent
	 */
	public void setName(String name);

	/**
	 * Returns the parent grand parent ID of this grand parent.
	 *
	 * @return the parent grand parent ID of this grand parent
	 */
	public long getParentGrandParentId();

	/**
	 * Sets the parent grand parent ID of this grand parent.
	 *
	 * @param parentGrandParentId the parent grand parent ID of this grand parent
	 */
	public void setParentGrandParentId(long parentGrandParentId);

	@Override
	public GrandParent cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}