/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Parent service. Represents a row in the &quot;Parent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.change.tracking.sample.model.impl.ParentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.change.tracking.sample.model.impl.ParentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Parent
 * @generated
 */
@ProviderType
public interface ParentModel
	extends BaseModel<Parent>, CTModel<Parent>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parent model instance should use the {@link Parent} interface instead.
	 */

	/**
	 * Returns the primary key of this parent.
	 *
	 * @return the primary key of this parent
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parent.
	 *
	 * @param primaryKey the primary key of this parent
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this parent.
	 *
	 * @return the mvcc version of this parent
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this parent.
	 *
	 * @param mvccVersion the mvcc version of this parent
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this parent.
	 *
	 * @return the ct collection ID of this parent
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this parent.
	 *
	 * @param ctCollectionId the ct collection ID of this parent
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the parent ID of this parent.
	 *
	 * @return the parent ID of this parent
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this parent.
	 *
	 * @param parentId the parent ID of this parent
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the company ID of this parent.
	 *
	 * @return the company ID of this parent
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this parent.
	 *
	 * @param companyId the company ID of this parent
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this parent.
	 *
	 * @return the name of this parent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this parent.
	 *
	 * @param name the name of this parent
	 */
	public void setName(String name);

	/**
	 * Returns the grand parent ID of this parent.
	 *
	 * @return the grand parent ID of this parent
	 */
	public long getGrandParentId();

	/**
	 * Sets the grand parent ID of this parent.
	 *
	 * @param grandParentId the grand parent ID of this parent
	 */
	public void setGrandParentId(long grandParentId);

	@Override
	public Parent cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}