/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model.impl;

import com.liferay.change.tracking.sample.model.Child;
import com.liferay.change.tracking.sample.model.ChildModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Child service. Represents a row in the &quot;Child&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChildModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChildImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChildImpl
 * @generated
 */
public class ChildModelImpl extends BaseModelImpl<Child> implements ChildModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a child model instance should use the <code>Child</code> interface instead.
	 */
	public static final String TABLE_NAME = "Child";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"childId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"grandParentId", Types.BIGINT},
		{"parentChildId", Types.BIGINT}, {"parentName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("grandParentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentChildId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Child (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,childId LONG not null,companyId LONG,name VARCHAR(75) null,grandParentId LONG,parentChildId LONG,parentName VARCHAR(75) null,primary key (childId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table Child";

	public static final String ORDER_BY_JPQL = " ORDER BY child.childId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Child.childId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GRANDPARENTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTCHILDID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHILDID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ChildModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _childId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChildId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _childId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Child.class;
	}

	@Override
	public String getModelClassName() {
		return Child.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Child, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Child, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Child, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Child)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Child, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Child, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Child)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Child, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Child, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Child, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Child, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Child, Object>>();

			attributeGetterFunctions.put("mvccVersion", Child::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", Child::getCtCollectionId);
			attributeGetterFunctions.put("childId", Child::getChildId);
			attributeGetterFunctions.put("companyId", Child::getCompanyId);
			attributeGetterFunctions.put("name", Child::getName);
			attributeGetterFunctions.put(
				"grandParentId", Child::getGrandParentId);
			attributeGetterFunctions.put(
				"parentChildId", Child::getParentChildId);
			attributeGetterFunctions.put("parentName", Child::getParentName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Child, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Child, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Child, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion", (BiConsumer<Child, Long>)Child::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<Child, Long>)Child::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"childId", (BiConsumer<Child, Long>)Child::setChildId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Child, Long>)Child::setCompanyId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Child, String>)Child::setName);
			attributeSetterBiConsumers.put(
				"grandParentId",
				(BiConsumer<Child, Long>)Child::setGrandParentId);
			attributeSetterBiConsumers.put(
				"parentChildId",
				(BiConsumer<Child, Long>)Child::setParentChildId);
			attributeSetterBiConsumers.put(
				"parentName", (BiConsumer<Child, String>)Child::setParentName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getChildId() {
		return _childId;
	}

	@Override
	public void setChildId(long childId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_childId = childId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public long getGrandParentId() {
		return _grandParentId;
	}

	@Override
	public void setGrandParentId(long grandParentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grandParentId = grandParentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGrandParentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("grandParentId"));
	}

	@Override
	public long getParentChildId() {
		return _parentChildId;
	}

	@Override
	public void setParentChildId(long parentChildId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentChildId = parentChildId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentChildId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentChildId"));
	}

	@Override
	public String getParentName() {
		if (_parentName == null) {
			return "";
		}
		else {
			return _parentName;
		}
	}

	@Override
	public void setParentName(String parentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentName = parentName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Child.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Child toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Child>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChildImpl childImpl = new ChildImpl();

		childImpl.setMvccVersion(getMvccVersion());
		childImpl.setCtCollectionId(getCtCollectionId());
		childImpl.setChildId(getChildId());
		childImpl.setCompanyId(getCompanyId());
		childImpl.setName(getName());
		childImpl.setGrandParentId(getGrandParentId());
		childImpl.setParentChildId(getParentChildId());
		childImpl.setParentName(getParentName());

		childImpl.resetOriginalValues();

		return childImpl;
	}

	@Override
	public Child cloneWithOriginalValues() {
		ChildImpl childImpl = new ChildImpl();

		childImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		childImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		childImpl.setChildId(this.<Long>getColumnOriginalValue("childId"));
		childImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		childImpl.setName(this.<String>getColumnOriginalValue("name"));
		childImpl.setGrandParentId(
			this.<Long>getColumnOriginalValue("grandParentId"));
		childImpl.setParentChildId(
			this.<Long>getColumnOriginalValue("parentChildId"));
		childImpl.setParentName(
			this.<String>getColumnOriginalValue("parentName"));

		return childImpl;
	}

	@Override
	public int compareTo(Child child) {
		long primaryKey = child.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Child)) {
			return false;
		}

		Child child = (Child)object;

		long primaryKey = child.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Child> toCacheModel() {
		ChildCacheModel childCacheModel = new ChildCacheModel();

		childCacheModel.mvccVersion = getMvccVersion();

		childCacheModel.ctCollectionId = getCtCollectionId();

		childCacheModel.childId = getChildId();

		childCacheModel.companyId = getCompanyId();

		childCacheModel.name = getName();

		String name = childCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			childCacheModel.name = null;
		}

		childCacheModel.grandParentId = getGrandParentId();

		childCacheModel.parentChildId = getParentChildId();

		childCacheModel.parentName = getParentName();

		String parentName = childCacheModel.parentName;

		if ((parentName != null) && (parentName.length() == 0)) {
			childCacheModel.parentName = null;
		}

		return childCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Child, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Child, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Child, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Child)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Child>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Child.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _childId;
	private long _companyId;
	private String _name;
	private long _grandParentId;
	private long _parentChildId;
	private String _parentName;

	public <T> T getColumnValue(String columnName) {
		Function<Child, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Child)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("childId", _childId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("grandParentId", _grandParentId);
		_columnOriginalValues.put("parentChildId", _parentChildId);
		_columnOriginalValues.put("parentName", _parentName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("childId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("name", 16L);

		columnBitmasks.put("grandParentId", 32L);

		columnBitmasks.put("parentChildId", 64L);

		columnBitmasks.put("parentName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Child _escapedModel;

}