/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model.impl;

import com.liferay.change.tracking.sample.model.Child;
import com.liferay.change.tracking.sample.service.ChildLocalServiceUtil;

/**
 * The extended model base implementation for the Child service. Represents a row in the &quot;Child&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChildImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChildImpl
 * @see Child
 * @generated
 */
public abstract class ChildBaseImpl extends ChildModelImpl implements Child {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a child model instance should use the <code>Child</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ChildLocalServiceUtil.addChild(this);
		}
		else {
			ChildLocalServiceUtil.updateChild(this);
		}
	}

}