/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model.impl;

import com.liferay.change.tracking.sample.model.GrandParent;
import com.liferay.change.tracking.sample.service.GrandParentLocalServiceUtil;

/**
 * The extended model base implementation for the GrandParent service. Represents a row in the &quot;GrandParent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GrandParentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GrandParentImpl
 * @see GrandParent
 * @generated
 */
public abstract class GrandParentBaseImpl
	extends GrandParentModelImpl implements GrandParent {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a grand parent model instance should use the <code>GrandParent</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GrandParentLocalServiceUtil.addGrandParent(this);
		}
		else {
			GrandParentLocalServiceUtil.updateGrandParent(this);
		}
	}

}