/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.change.tracking.sample.model.impl;

import com.liferay.change.tracking.sample.model.Parent;
import com.liferay.change.tracking.sample.service.ParentLocalServiceUtil;

/**
 * The extended model base implementation for the Parent service. Represents a row in the &quot;Parent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParentImpl
 * @see Parent
 * @generated
 */
public abstract class ParentBaseImpl extends ParentModelImpl implements Parent {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parent model instance should use the <code>Parent</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ParentLocalServiceUtil.addParent(this);
		}
		else {
			ParentLocalServiceUtil.updateParent(this);
		}
	}

}