/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portlet.asset.service.base;

import com.liferay.asset.kernel.model.AssetVocabularyDepotEntryRel;
import com.liferay.asset.kernel.service.AssetVocabularyDepotEntryRelService;
import com.liferay.asset.kernel.service.AssetVocabularyDepotEntryRelServiceUtil;
import com.liferay.asset.kernel.service.persistence.AssetVocabularyDepotEntryRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset vocabulary depot entry rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.asset.service.impl.AssetVocabularyDepotEntryRelServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.asset.service.impl.AssetVocabularyDepotEntryRelServiceImpl
 * @generated
 */
public abstract class AssetVocabularyDepotEntryRelServiceBaseImpl
	extends BaseServiceImpl
	implements AssetVocabularyDepotEntryRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetVocabularyDepotEntryRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssetVocabularyDepotEntryRelServiceUtil</code>.
	 */

	/**
	 * Returns the asset vocabulary depot entry rel local service.
	 *
	 * @return the asset vocabulary depot entry rel local service
	 */
	public
		com.liferay.asset.kernel.service.
			AssetVocabularyDepotEntryRelLocalService
				getAssetVocabularyDepotEntryRelLocalService() {

		return assetVocabularyDepotEntryRelLocalService;
	}

	/**
	 * Sets the asset vocabulary depot entry rel local service.
	 *
	 * @param assetVocabularyDepotEntryRelLocalService the asset vocabulary depot entry rel local service
	 */
	public void setAssetVocabularyDepotEntryRelLocalService(
		com.liferay.asset.kernel.service.
			AssetVocabularyDepotEntryRelLocalService
				assetVocabularyDepotEntryRelLocalService) {

		this.assetVocabularyDepotEntryRelLocalService =
			assetVocabularyDepotEntryRelLocalService;
	}

	/**
	 * Returns the asset vocabulary depot entry rel remote service.
	 *
	 * @return the asset vocabulary depot entry rel remote service
	 */
	public AssetVocabularyDepotEntryRelService
		getAssetVocabularyDepotEntryRelService() {

		return assetVocabularyDepotEntryRelService;
	}

	/**
	 * Sets the asset vocabulary depot entry rel remote service.
	 *
	 * @param assetVocabularyDepotEntryRelService the asset vocabulary depot entry rel remote service
	 */
	public void setAssetVocabularyDepotEntryRelService(
		AssetVocabularyDepotEntryRelService
			assetVocabularyDepotEntryRelService) {

		this.assetVocabularyDepotEntryRelService =
			assetVocabularyDepotEntryRelService;
	}

	/**
	 * Returns the asset vocabulary depot entry rel persistence.
	 *
	 * @return the asset vocabulary depot entry rel persistence
	 */
	public AssetVocabularyDepotEntryRelPersistence
		getAssetVocabularyDepotEntryRelPersistence() {

		return assetVocabularyDepotEntryRelPersistence;
	}

	/**
	 * Sets the asset vocabulary depot entry rel persistence.
	 *
	 * @param assetVocabularyDepotEntryRelPersistence the asset vocabulary depot entry rel persistence
	 */
	public void setAssetVocabularyDepotEntryRelPersistence(
		AssetVocabularyDepotEntryRelPersistence
			assetVocabularyDepotEntryRelPersistence) {

		this.assetVocabularyDepotEntryRelPersistence =
			assetVocabularyDepotEntryRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		AssetVocabularyDepotEntryRelServiceUtil.setService(
			assetVocabularyDepotEntryRelService);
	}

	public void destroy() {
		AssetVocabularyDepotEntryRelServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetVocabularyDepotEntryRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetVocabularyDepotEntryRel.class;
	}

	protected String getModelClassName() {
		return AssetVocabularyDepotEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			assetVocabularyDepotEntryRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.asset.kernel.service.AssetVocabularyDepotEntryRelLocalService.class
	)
	protected
		com.liferay.asset.kernel.service.
			AssetVocabularyDepotEntryRelLocalService
				assetVocabularyDepotEntryRelLocalService;

	@BeanReference(type = AssetVocabularyDepotEntryRelService.class)
	protected AssetVocabularyDepotEntryRelService
		assetVocabularyDepotEntryRelService;

	@BeanReference(type = AssetVocabularyDepotEntryRelPersistence.class)
	protected AssetVocabularyDepotEntryRelPersistence
		assetVocabularyDepotEntryRelPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetVocabularyDepotEntryRelServiceBaseImpl.class);

}