/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.tags.model.impl;

import com.liferay.asset.tags.model.AssetTagDepotEntryRel;
import com.liferay.asset.tags.service.AssetTagDepotEntryRelLocalServiceUtil;

/**
 * The extended model base implementation for the AssetTagDepotEntryRel service. Represents a row in the &quot;AssetTagDepotEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetTagDepotEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetTagDepotEntryRelImpl
 * @see AssetTagDepotEntryRel
 * @generated
 */
public abstract class AssetTagDepotEntryRelBaseImpl
	extends AssetTagDepotEntryRelModelImpl implements AssetTagDepotEntryRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset tag depot entry rel model instance should use the <code>AssetTagDepotEntryRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AssetTagDepotEntryRelLocalServiceUtil.addAssetTagDepotEntryRel(
				this);
		}
		else {
			AssetTagDepotEntryRelLocalServiceUtil.updateAssetTagDepotEntryRel(
				this);
		}
	}

}