/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.tags.model.impl;

import com.liferay.asset.tags.model.AssetTagDepotEntryRel;
import com.liferay.asset.tags.model.AssetTagDepotEntryRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssetTagDepotEntryRel service. Represents a row in the &quot;AssetTagDepotEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssetTagDepotEntryRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetTagDepotEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetTagDepotEntryRelImpl
 * @generated
 */
@JSON(strict = true)
public class AssetTagDepotEntryRelModelImpl
	extends BaseModelImpl<AssetTagDepotEntryRel>
	implements AssetTagDepotEntryRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset tag depot entry rel model instance should use the <code>AssetTagDepotEntryRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "AssetTagDepotEntryRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"assetTagDepotEntryRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"assetTagId", Types.BIGINT},
		{"depotEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetTagDepotEntryRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetTagId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("depotEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AssetTagDepotEntryRel (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,assetTagDepotEntryRelId LONG not null,companyId LONG,assetTagId LONG,depotEntryId LONG,primary key (assetTagDepotEntryRelId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table AssetTagDepotEntryRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assetTagDepotEntryRel.assetTagDepotEntryRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AssetTagDepotEntryRel.assetTagDepotEntryRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETTAGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPOTENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETTAGDEPOTENTRYRELID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AssetTagDepotEntryRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetTagDepotEntryRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetTagDepotEntryRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetTagDepotEntryRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetTagDepotEntryRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetTagDepotEntryRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssetTagDepotEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssetTagDepotEntryRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetTagDepotEntryRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AssetTagDepotEntryRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssetTagDepotEntryRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssetTagDepotEntryRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssetTagDepotEntryRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssetTagDepotEntryRel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssetTagDepotEntryRel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AssetTagDepotEntryRel, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AssetTagDepotEntryRel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AssetTagDepotEntryRel, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", AssetTagDepotEntryRel::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", AssetTagDepotEntryRel::getCtCollectionId);
			attributeGetterFunctions.put(
				"uuid", AssetTagDepotEntryRel::getUuid);
			attributeGetterFunctions.put(
				"assetTagDepotEntryRelId",
				AssetTagDepotEntryRel::getAssetTagDepotEntryRelId);
			attributeGetterFunctions.put(
				"companyId", AssetTagDepotEntryRel::getCompanyId);
			attributeGetterFunctions.put(
				"assetTagId", AssetTagDepotEntryRel::getAssetTagId);
			attributeGetterFunctions.put(
				"depotEntryId", AssetTagDepotEntryRel::getDepotEntryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AssetTagDepotEntryRel, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AssetTagDepotEntryRel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AssetTagDepotEntryRel, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AssetTagDepotEntryRel, String>)
					AssetTagDepotEntryRel::setUuid);
			attributeSetterBiConsumers.put(
				"assetTagDepotEntryRelId",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setAssetTagDepotEntryRelId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setCompanyId);
			attributeSetterBiConsumers.put(
				"assetTagId",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setAssetTagId);
			attributeSetterBiConsumers.put(
				"depotEntryId",
				(BiConsumer<AssetTagDepotEntryRel, Long>)
					AssetTagDepotEntryRel::setDepotEntryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAssetTagDepotEntryRelId() {
		return _assetTagDepotEntryRelId;
	}

	@Override
	public void setAssetTagDepotEntryRelId(long assetTagDepotEntryRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetTagDepotEntryRelId = assetTagDepotEntryRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getAssetTagId() {
		return _assetTagId;
	}

	@Override
	public void setAssetTagId(long assetTagId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetTagId = assetTagId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssetTagId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assetTagId"));
	}

	@JSON
	@Override
	public long getDepotEntryId() {
		return _depotEntryId;
	}

	@Override
	public void setDepotEntryId(long depotEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_depotEntryId = depotEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDepotEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("depotEntryId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssetTagDepotEntryRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetTagDepotEntryRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssetTagDepotEntryRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetTagDepotEntryRelImpl assetTagDepotEntryRelImpl =
			new AssetTagDepotEntryRelImpl();

		assetTagDepotEntryRelImpl.setMvccVersion(getMvccVersion());
		assetTagDepotEntryRelImpl.setCtCollectionId(getCtCollectionId());
		assetTagDepotEntryRelImpl.setUuid(getUuid());
		assetTagDepotEntryRelImpl.setAssetTagDepotEntryRelId(
			getAssetTagDepotEntryRelId());
		assetTagDepotEntryRelImpl.setCompanyId(getCompanyId());
		assetTagDepotEntryRelImpl.setAssetTagId(getAssetTagId());
		assetTagDepotEntryRelImpl.setDepotEntryId(getDepotEntryId());

		assetTagDepotEntryRelImpl.resetOriginalValues();

		return assetTagDepotEntryRelImpl;
	}

	@Override
	public AssetTagDepotEntryRel cloneWithOriginalValues() {
		AssetTagDepotEntryRelImpl assetTagDepotEntryRelImpl =
			new AssetTagDepotEntryRelImpl();

		assetTagDepotEntryRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		assetTagDepotEntryRelImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		assetTagDepotEntryRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		assetTagDepotEntryRelImpl.setAssetTagDepotEntryRelId(
			this.<Long>getColumnOriginalValue("assetTagDepotEntryRelId"));
		assetTagDepotEntryRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		assetTagDepotEntryRelImpl.setAssetTagId(
			this.<Long>getColumnOriginalValue("assetTagId"));
		assetTagDepotEntryRelImpl.setDepotEntryId(
			this.<Long>getColumnOriginalValue("depotEntryId"));

		return assetTagDepotEntryRelImpl;
	}

	@Override
	public int compareTo(AssetTagDepotEntryRel assetTagDepotEntryRel) {
		long primaryKey = assetTagDepotEntryRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssetTagDepotEntryRel)) {
			return false;
		}

		AssetTagDepotEntryRel assetTagDepotEntryRel =
			(AssetTagDepotEntryRel)object;

		long primaryKey = assetTagDepotEntryRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetTagDepotEntryRel> toCacheModel() {
		AssetTagDepotEntryRelCacheModel assetTagDepotEntryRelCacheModel =
			new AssetTagDepotEntryRelCacheModel();

		assetTagDepotEntryRelCacheModel.mvccVersion = getMvccVersion();

		assetTagDepotEntryRelCacheModel.ctCollectionId = getCtCollectionId();

		assetTagDepotEntryRelCacheModel.uuid = getUuid();

		String uuid = assetTagDepotEntryRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assetTagDepotEntryRelCacheModel.uuid = null;
		}

		assetTagDepotEntryRelCacheModel.assetTagDepotEntryRelId =
			getAssetTagDepotEntryRelId();

		assetTagDepotEntryRelCacheModel.companyId = getCompanyId();

		assetTagDepotEntryRelCacheModel.assetTagId = getAssetTagId();

		assetTagDepotEntryRelCacheModel.depotEntryId = getDepotEntryId();

		return assetTagDepotEntryRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssetTagDepotEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssetTagDepotEntryRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetTagDepotEntryRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AssetTagDepotEntryRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AssetTagDepotEntryRel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AssetTagDepotEntryRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _assetTagDepotEntryRelId;
	private long _companyId;
	private long _assetTagId;
	private long _depotEntryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AssetTagDepotEntryRel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AssetTagDepotEntryRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"assetTagDepotEntryRelId", _assetTagDepotEntryRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("assetTagId", _assetTagId);
		_columnOriginalValues.put("depotEntryId", _depotEntryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("assetTagDepotEntryRelId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("assetTagId", 32L);

		columnBitmasks.put("depotEntryId", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AssetTagDepotEntryRel _escapedModel;

}